name: Russell Square Travel Company
favicon: null
layout_spectrum: 0.7437
typography_spectrum: 0.2411898
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Russell Square Travel Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8a2020'
    - '#ac9a8e'
    - '#ffcaac'
    - '#3e8ee3'
    - '#073c7e'
  brandStrength: 0.7257825
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
