layout_spectrum: 0.5735651
typography_spectrum: 0.2411898
color:
  saturation: 0.1327932
  lightness: 0.2923505
  brandStrength: 0.7257825
  rhythmicContrast: 0.8149141
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Russell Square Travel Company
